apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-test
build:
  artifacts:
  - image: hello
    context: hello
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - hello/deployment/app.yml
    - hello/deployment/ingress.yml